=== bergermaestro/personal-website-astro/.astro/collections/books.schema.json
{
  "$ref": "#/definitions/books",
  "definitions": {
    "books": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "released": {
          "type": "number"
        },
        "author": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "enum": [
            "to read",
            "currently reading",
            "finished"
          ]
        },
        "rating": {
          "type": "number"
        },
        "finished_on": {
          "type": "string"
        },
        "cover": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "isbn": {
          "type": "number"
        }
      },
      "required": [
        "title",
        "released",
        "author",
        "status",
        "cover"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== bergermaestro/personal-website-astro/src/data/json/books.json
[
  {
    "title": "Artemis",
    "released": 2017,
    "author": "Andy Weir",
    "status": "finished",
    "rating": 9,
    "finished_on": "August 2024",
    "cover": "../images/books/artemis.jpg"
  },
  {
    "title": "Fractal Noise",
    "released": 2023,
    "author": "Christopher Paolini",
    "status": "finished",
    "rating": 5,
    "finished_on": "August 2024",
    "cover": "../images/books/fractal-noise.jpg"
  },
  {
    "title": "The Apollo Murders",
    "released": 2021,
    "author": "Chris Hadfield",
    "status": "finished",
    "rating": 9,
    "finished_on": "December 2023",
    "cover": "../images/books/the-apollo-murders.webp"
  },
  {
    "title": "The Martian",
    "released": 2011,
    "author": "Andy Weir",
    "status": "finished",
    "rating": 9,
    "finished_on": "July 2024",
    "cover": "../images/books/the-martian.webp"
  },
  {
    "title": "The Rural Voter",
    "released": 2023,
    "author": "Nicholas F. Jacobs and Daniel M. Shea",
    "status": "finished",
    "rating": 8,
    "finished_on": "December 2024",
    "cover": "../images/books/the-rural-voter.jpg"
  },
  {
    "title": "War",
    "released": 2024,
    "author": "Bob Woodward",
    "status": "to read",
    "rating": null,
    "finished_on": null,
    "cover": "../images/books/war.jpg"
  },
  {
    "title": "The Other Significant Others",
    "released": 2024,
    "author": "Rhaina Cohen",
    "status": "to read",
    "rating": null,
    "finished_on": null,
    "cover": "../images/books/other-significant-others.jpg"
  },
  {
    "title": "Moby Dick",
    "released": 1851,
    "author": "Herman Melville",
    "status": "currently reading",
    "rating": null,
    "finished_on": null,
    "cover": "../images/books/artemis.jpg"
  },
  {
    "title": "The Alchemist",
    "released": 1988,
    "author": "Paulo Coelho",
    "status": "finished",
    "rating": 7,
    "finished_on": "October 2022",
    "cover": "../images/books/artemis.jpg"
  },
  {
    "title": "War and Peace",
    "released": 1869,
    "author": "Leo Tolstoy",
    "status": "to read",
    "rating": null,
    "finished_on": null,
    "cover": "../images/books/artemis.jpg"
  }
]

=== bergermaestro/personal-website-astro/src/data/books/books.json
[
  {
    "title": "Artemis",
    "released": 2017,
    "author": "Andy Weir",
    "status": "finished",
    "rating": 9,
    "finished_on": "August 2024",
    "cover": "../images/books/artemis.jpg",
    "isbn": 9780553448146
  },
  {
    "title": "Fractal Noise",
    "released": 2023,
    "author": "Christopher Paolini",
    "status": "finished",
    "rating": 5,
    "finished_on": "August 2024",
    "cover": "../images/books/fractal-noise.jpg",
    "isbn": 9781250292100
  },
  {
    "title": "The Apollo Murders",
    "released": 2021,
    "author": "Chris Hadfield",
    "status": "finished",
    "rating": 9,
    "finished_on": "December 2023",
    "cover": "../images/books/the-apollo-murders.webp",
    "isbn": 9780316264532
  },
  {
    "title": "The Martian",
    "released": 2011,
    "author": "Andy Weir",
    "status": "finished",
    "rating": 9,
    "finished_on": "July 2024",
    "cover": "../images/books/the-martian.webp",
    "isbn": 9780553418026
  },
  {
    "title": "The Rural Voter",
    "released": 2023,
    "author": "Nicholas F. Jacobs and Daniel M. Shea",
    "status": "finished",
    "rating": 8,
    "finished_on": "December 2024",
    "cover": "../images/books/the-rural-voter.jpg",
    "isbn": 9780231218573
  },
  {
    "title": "War",
    "released": 2024,
    "author": "Bob Woodward",
    "status": "to read",
    "cover": "../images/books/war.jpg",
    "isbn": 9781668052273
  },
  {
    "title": "The Other Significant Others",
    "released": 2024,
    "author": "Rhaina Cohen",
    "status": "finished",
    "rating": 10,
    "finished_on": "January 2025",
    "cover": "../images/books/other-significant-others.jpg",
    "isbn": 9781250280916
  },
  {
    "title": "Frankenstein",
    "released": 1818,
    "author": "Mary Shelley",
    "status": "to read",
    "cover": "../images/books/frankenstein.jpg",
    "url": "https://www.gutenberg.org/files/84/84-h/84-h.htm"
  },
  {
    "title": "As I Walked About",
    "released": 2020,
    "author": "Phil Jenkins",
    "status": "to read",
    "cover": "../images/books/as-i-walked-about.webp",
    "isbn": 9781988437392
  },
  {
    "title": "Dead Wake",
    "released": 2015,
    "author": "Erik Larson",
    "status": "finished",
    "rating": 9,
    "finished_on": "March 2025",
    "cover": "../images/books/dead-wake.jpg",
    "isbn": 9780307408877
  },
  {
    "title": "When We Cease to Understand the World",
    "released": 2020,
    "author": "Benjamín Labatut",
    "status": "finished",
    "rating": 9,
    "finished_on": "July 2025",
    "cover": "../images/books/cease-to-understand-the-world.jpg",
    "isbn": 9781681375663
  },
  {
    "title": "The Revenge of Power",
    "released": 2022,
    "author": "Moisés Naim",
    "status": "finished",
    "cover": "../images/books/revenge-of-power.jpg",
    "isbn": 9781250875822,
    "rating": 9,
    "finished_on": "March 2025"
  },
  {
    "title": "The War We Won Apart",
    "released": 2024,
    "author": "Nahlah Ayed",
    "status": "finished",
    "cover": "../images/books/war-we-won-apart.jpg",
    "isbn": 9780735242067,
    "rating": 9,
    "finished_on": "September 2025"
  },
  {
    "title": "Lessons in Chemistry",
    "released": 2022,
    "author": "Bonnie Garmus",
    "status": "to read",
    "cover": "../images/books/lessons-in-chemistry.jpg",
    "isbn": 9780385697378
  },
  {
    "title": "Who Moved My Cheese?",
    "author": "Spencer Johnson",
    "released": 1998,
    "status": "finished",
    "cover": "../images/books/who-moved-my-cheese.jpg",
    "rating": 7,
    "finished_on": "March 2025",
    "isbn": 9780091816971
  },
  {
    "title": "Original Sin",
    "author": "Jake Tapper and Alex Thompson",
    "released": 2025,
    "status": "finished",
    "cover": "../images/books/original-sin.jpg",
    "rating": 8,
    "finished_on": "June 2025",
    "isbn": 9798217060672
  },
  {
    "title": "Amusing Ourselves to Death",
    "author": "Neil Postman",
    "released": 1985,
    "status": "finished",
    "cover": "../images/books/amusing-ourselves-to-death.jpg",
    "rating": 10,
    "finished_on": "April 2025",
    "isbn": 9780143036531
  },
  {
    "title": "The Ascent of Money",
    "author": "Niall Ferguson",
    "released": 2008,
    "status": "to read",
    "cover": "../images/books/the-ascent-of-money.jpg",
    "isbn": 9780143116172
  },
  {
    "title": "The Whisper on the Night Wind",
    "author": "Adam Shoalts",
    "released": 2021,
    "status": "finished",
    "cover": "../images/books/whisper-night-wind.jpg",
    "isbn": 9780735241060,
    "rating": 9,
    "finished_on": "October 2025"
  },
  {
    "title": "Vanished Beyond the Map",
    "author": "Adam Shoalts",
    "released": 2025,
    "status": "finished",
    "cover": "../images/books/vanished-beyond-the-map.avif",
    "isbn": 9780735236868,
    "rating": 10,
    "finished_on": "November 2025"
  },
  {
    "title": "The Shortest History of Economics",
    "author": "Andrew Leigh",
    "released": 2024,
    "status": "finished",
    "cover": "../images/books/shortest-history-economics.jpg",
    "isbn": 9781760644000,
    "rating": 10,
    "finished_on": "December 2025"
  },
  {
    "title": "The Screwtape Letters",
    "author": "C.S. Lewis",
    "released": 1942,
    "status": "finished",
    "cover": "../images/books/screwtape-letters.jpg",
    "isbn": 9780060652937,
    "rating": 8,
    "finished_on": "January 2026"
  },
  {
    "title": "Project Hail Mary",
    "author": "Andy Weir",
    "released": 2021,
    "status": "finished",
    "cover": "../images/books/project-hail-mary.jpg",
    "isbn": 9780593135204,
    "rating": 10,
    "finished_on": "March 2026"
  },
  {
    "title": "Six of Crows",
    "author": "Leigh Bardugo",
    "released": 2015,
    "status": "finished",
    "cover": "../images/books/six-of-crows.avif",
    "isbn": 9781250076960,
    "rating": 9,
    "finished_on": "April 2026"
  },
  {
    "title": "Crooked Kingdom",
    "author": "Leigh Bardugo",
    "released": 2016,
    "status": "currently reading",
    "cover": "../images/books/crooked-kingdom.avif",
    "isbn": 9781250076977
  }
]
